name: Deploy to Azure App Service

on:
  push:
    branches:
      - fp-back-end
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'  # Updated to Node 20.18.0 from 14.x
        
      - name: Install Dependencies
        run: npm install
        
      - name: Build Project (if necessary)
        run: npm run build  # Only if you have a build step

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fp-back-end'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .